version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    image: your_application_image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL=postgres://root:password@db:5432/NEOGYM
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 
      POSTGRES_DB: NEOGYM
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: