name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dhw972300@gmail.com }}
          password: ${{ secrets.Hung4864 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.dhw972300@gmail.com }}/my-devops:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: your-server
          username: dhw972300@gmail.com
          key: ${{ secrets.DOCKER_DOANHUNG9723 }}
          script: |
            docker pull ${{ secrets.dhw972300@gmail.com }}/my-devops:latest
            docker-compose up -d

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.dhw972300@gmail.com }}
          password: ${{ secrets.Hung4864 }}
          subject: Deployment Notification
          body: The deployment to production was successful.
          to: dhw972300@gmail.com
          from: dhw972300@gmail.com


